# Generated by Django 3.2.4 on 2021-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='img_url',
            field=models.URLField(default='https://picsum.photos/1000/'),
        ),
    ]
